import os
import regex as re
from shutil import copyfile

INPUT_DIR = '/Users/david/Documents/MacTutor/actual-work/datasheets/'

BOOKPAGES = ['Abel4.gif',
    'Aiken_machine.jpeg',
    'Al\'Khwarizmi4a.gif',
    'Al\'Khwarizmi4b.gif',
    'Al\'Khwarizmi4c.gif',
    'Al-Khwarizmi4a.gif',
    'Al-Khwarizmi4b.gif',
    'Al-Khwarizmi4c.gif',
    'Alberti.jpeg',
    'Apollonius3.gif',
    'Apollonius5.gif',
    'Archimedes3.gif',
    'Argand9.gif',
    'Babbage10.jpeg',
    'Bacon2.jpeg',
    'Barrow7a.gif',
    'Barrow7b.gif',
    'Berkeley2.gif',
    'Berkeley2a.gif',
    'Berkeley7.gif',
    'Bernoulli10.gif',
    'Bolzano10a.gif',
    'Bolzano10b.gif',
    'Bombelli4.gif',
    'Bombelli4b.gif',
    'Boole9.gif',
    'Boole_1.jpg',
    'Boole_2.jpg',
    'Boole_3.jpg',
    'Boole_4.jpg',
    'Boole_5.jpg',
    'Boole_6.jpg',
    'Briggs1.gif',
    'Cantor10a.gif',
    'Cantor10b.gif',
    'Cantor10c.gif',
    'Cardan4.gif',
    'Cataldi8a.gif',
    'Cataldi8b.gif',
    'Cavalieri7.gif',
    'Cavalieri7b.gif',
    'Chuquet4.gif',
    'Clairaut6.gif',
    'Cramer9.gif',
    'DeMoivre10.gif',
    'Desargues5a.gif',
    'Desargues5b.gif',
    'Desargues5c.gif',
    'Descartes3.gif',
    'Descartes4.gif',
    'Descartes6a.gif',
    'Descartes6b.gif',
    'Diophantus4a.gif',
    'Diophantus4b.gif',
    'Durer.jpeg',
    'ENIAC.jpeg',
    'Euclid10a.gif',
    'Euclid10b.gif',
    'Euclid2.gif',
    'Euclid3a.gif',
    'Euclid3b.gif',
    'Euclid3c.gif',
    'Euclid3d.gif',
    'Euclid4a.gif',
    'Euclid4b.gif',
    'Euclid5.gif',
    'Euclid8.gif',
    'Euler6a.gif',
    'Euler6b.gif',
    'Fermat6.gif',
    'Fermat7.gif',
    'Frege10.gif',
    'Frege10.html',
    'Galileo10.gif',
    'Galileo2.gif',
    'Galileo7.gif',
    'Galois9.gif',
    'Gauss8.gif',
    'Gauss9.gif',
    'Gregory7.gif',
    'Gregory7b.gif',
    'Hamilton9.gif',
    'Hollerith_machine.jpeg',
    'Huygens10.gif',
    'Huygens7.gif',
    'Jordanus4.gif',
    'Lagrange9.gif',
    'Lambert5.gif',
    'Lambert8.gif',
    'Lansberge1.jpeg',
    'Lansberge2.jpeg',
    'Laplace10a.gif',
    'Laplace10b.gif',
    'Leibnitz9.gif',
    'Leibniz_machine.jpeg',
    'Leibniz_machine2.jpeg',
    'Leonardo.jpeg',
    'Maclaurin7.gif',
    'Maclaurin9.gif',
    'Maclaurin_Fluxions.gif',
    'Menabrea10.gif',
    'Mercator5.gif',
    'Metius1.gif',
    'Napier1.gif',
    'Napier10.jpeg',
    'Newton6.gif',
    'Newton7.gif',
    'Nichomachus1.gif',
    'Oresme6.gif',
    'Oughtred3.gif',
    'Pacioli4.gif',
    'Palimpest.jpeg',
    'Pappus3.gif',
    'Pappus3a.gif',
    'Pappus5.gif',
    'Peano10.gif',
    'Piero.jpeg',
    'Piero_0.jpeg',
    'Poisson10.gif',
    'Poncelet9.gif',
    'Pythagoras-Boethius1.gif',
    'Recorde1.jpeg',
    'Recorde2.jpeg',
    'Recorde4.gif',
    'Recorde4.jpeg',
    'Riemann8.gif',
    'Riemann8b.gif',
    'Ries.jpeg',
    'Roberval7.gif',
    'Saccheri8.gif',
    'Saccheri8b.gif',
    'Siliceus1.gif',
    'Siliceus2.gif',
    'Smith_DE_Rara.jpeg',
    'Steiner5.gif',
    'Stevin1.gif',
    'Stevin2.gif',
    'Stifel2.gif',
    'Stifel4.gif',
    'Sylvester9.gif',
    'Tacquet.jpg',
    'Tacquet_2.jpg',
    'Tacquet_3.jpg',
    'Tacquet_4.jpg',
    'Taylor5a.gif',
    'Taylor5b.gif',
    'Torricelli7.gif',
    'Van_Schooten6.gif',
    'Van_Schooten6.jpeg',
    'Viete1.gif',
    'Viete4.gif',
    'Von_Staudt5.gif',
    'Wallis7.gif',
    'Wallis8.gif',
    'merclog.jpg'
]

found = {}


pattern = re.compile(r'(?<=\D+)(\d)(?=.gif(.lr)?)')
for subdir, dirs, files in os.walk(INPUT_DIR):
    for file in files:
        path = os.path.join(subdir, file)
        if not os.path.isfile(path): continue

        with open(path, 'r', encoding='mac_roman') as f:
            data = f.read()

        for page in BOOKPAGES:
            if page in data:
                print('found!')
                if page in found:
                    found[page].append(file)
                else:
                    found[page] = [file]

print(found)
